services:
  admin:
    build:
      context: .
    tty: true
    volumes:
      - ./app:/app
    environment:
      - WATCHPACK_POLLING=true
    #npm ciで環境構築後にいづれかを有効にする
    #command: /bin/sh -c 'npm run dev'
    #command: /bin/sh -c 'npm run start'
    #command: /bin/sh -c 'npm run preview'
    #command: /bin/sh -c 'npm start'
    ports:
      - "1234:1234"
    #自動起動設定
    #systemctl enable docker.serviceも設定
    #restart: always

