---
:ws_server:        wss://demo-weborca.cloud.orcamo.jp/ws
:api_user:         ormaster
:api_key:          03b53f8cbb9904ba537c24e84d07f21cebaa381053aadc5e1a13f6c6e157734d
:api_server:       demo-weborca.cloud.orcamo.jp
:api_port:         443
:use_ssl:          true
:use_weborca:      true
:ca_cert:          "C:/push-exchanger/certs/root.crt"
:cert:             "C:/push-exchanger/certs/002739__JP_u00000218_client1349.crt"
:cert_key:         "C:/push-exchanger/certs/002739__JP_u00000218_client1349.pem"
:passphrase:       OMZoDP7hN0
:log_file:         "C:/push-exchanger/log/push-exchanger.log.txt"
:log_level:        debug
:plugin_load_path:
  - "C:/push-exchanger/plugin"